### ISSUE TITLE
Häufig besuchte Inhalte

### ISSUE THREAD

**Issue by bucherfa** [Webprogrammierung-B3/projekt#12]

**Comment by anaklysmos** [comment]
"Gegeben sei das Cassidy die Webanwendung schon einmal erfolgreich aufgerufen hat.
Wenn die Startseite vollständig geladen wurde,
dann werden Cassidy ihre meist besuchten Inhalte angezeigt."

**Comment by bucherfa** [comment]
* startseite anzeigen
