### ISSUE TITLE
Favoriten

### ISSUE THREAD

**Issue by bucherfa** [Webprogrammierung-B3/projekt#13]

**Comment by anaklysmos** [comment]
Gegeben sei das Cassidy die Webanwendung schon einmal erfolgreich aufgerufen hat.
Wenn eine Inhaltsseite vollständig geladen wurde,
dann kann Cassidy Inhalten als Favorit zu markieren
und die Markierung wird auf dem Backend ihrer Sitzung zugeordnet.

Gegeben sei das Cassidy bereits Inhalte als Favorit markiert hat.
Wenn eine Inhaltsseite vollständig geladen wurde,
dann werden Cassidy ihre favorisierten Inhalte anhand ihres Personalisierungsmerkmals angezeigt.

Gegeben sei das Bryn die Webanwendung zum ersten Mal aufruft
und das Cassidy bereits Inhalte als Favorit markiert hat.
Wenn die Anwendung vollständig geladen wurde,
dann werden Bryn keine Favoriten angezeigt.

**Comment by bucherfa** [comment]
* auf der startseite anzeigen
* favoriten button -> state anzeigen
