### ISSUE TITLE
Kommentare

### ISSUE THREAD

**Issue by bucherfa** [Webprogrammierung-B3/projekt#14]

**Comment by anaklysmos** [comment]
Gegeben sei das Cassidy die Webanwendung schon einmal erfolgreich aufgerufen hat.
Wenn eine Inhaltsseite vollständig geladen wurde,
dann kann Cassidy Kommentare zu Inhalten zu erstellen
und der Kommentar wird auf dem Backend ihrer Sitzung zugeordnet.

Gegeben sei das Cassidy bereits Kommentare erstellt hat.
Wenn eine Inhaltsseite vollständig geladen wurde,
dann werden Cassidy ihre Kommentare anhand ihres Personalisierungsmerkmals angezeigt.

Gegeben sei das Bryn die Webanwendung zum ersten Mal aufruft
und das Cassidy bereits Kommentare erstellt hat.
Wenn die Anwendung vollständig geladen wurde,
dann werden Bryn alle Kommentare aller Sitzungen angezeigt.
